[package]
name = "fsb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.66"
flutter_rust_bridge = "= 1.82.3"
ipc-channel = "0.17.0"
lazy_static = "1.4.0"
serde = { version = "1.0.106", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
slint = "1.3.2"
tao = "0.24.0"
tray-icon = "0.11.0"
image = "0.24.7"

[build-dependencies]
flutter_rust_bridge_codegen = "= 1.82.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
