name: fsb_dart
description: flutter slint bridge
version: 0.1.0
publish_to: none

environment:
  sdk: '^3.1.0'

dependencies:
  flutter_rust_bridge: 1.82.6
  ffi: ^2.0.1


dev_dependencies:
  build_runner_core: ^7.2.9
  ffigen: ^9.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0